apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinity
  namespace: ragflow
  labels:
    app: infinity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infinity
  template:
    metadata:
      labels:
        app: infinity
    spec:
      containers:
      - name: infinity
        image: infiniflow/infinity:v0.6.0-dev5
        ports:
        - containerPort: 23817
        - containerPort: 23820
        - containerPort: 5432
        command:
        - infinity
        - -f
        - /infinity_conf.toml
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: ragflow-config
              key: TIMEZONE
        volumeMounts:
        - name: infinity-data
          mountPath: /var/infinity
        - name: infinity-config
          mountPath: /infinity_conf.toml
          subPath: infinity_conf.toml
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /admin/node/current
            port: 23820
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 120
        readinessProbe:
          httpGet:
            path: /admin/node/current
            port: 23820
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: infinity-data
        persistentVolumeClaim:
          claimName: infinity-pvc
      - name: infinity-config
        configMap:
          name: infinity-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: infinity-config
  namespace: ragflow
data:
  infinity_conf.toml: |
    [server]
    host = "0.0.0.0"
    port = 23817
    http_port = 23820
    psql_port = 5432
    
    [log]
    level = "info"
    
    [storage]
    data_path = "/var/infinity"
    
    [network]
    listen_addr = "0.0.0.0:23817"
    http_listen_addr = "0.0.0.0:23820"
    psql_listen_addr = "0.0.0.0:5432"
---
apiVersion: v1
kind: Service
metadata:
  name: infinity
  namespace: ragflow
  labels:
    app: infinity
spec:
  selector:
    app: infinity
  ports:
  - name: thrift
    port: 23817
    targetPort: 23817
  - name: http
    port: 23820
    targetPort: 23820
  - name: psql
    port: 5432
    targetPort: 5432
  type: ClusterIP
