apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: ragflow
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      securityContext:
        fsGroup: 999
        supplementalGroups: [999]
    
        image: mysql:8.0.39
        command:
        - /bin/bash
        - -c
        - |
          set -e
          echo "=== 开始初始化MySQL数据目录 ==="
          echo "当前用户: $(whoami)"
          echo "当前用户ID: $(id)"
          
          # 确保数据目录存在
          echo "创建数据目录..."
          mkdir -p /var/lib/mysql
          
          # 设置正确的权限
          echo "设置数据目录权限..."
          chown -R 999:999 /var/lib/mysql
          chmod -R 750 /var/lib/mysql
          
          # 检查是否需要初始化MySQL数据目录
          if [ ! -f "/var/lib/mysql/mysql/user.frm" ] && [ ! -f "/var/lib/mysql/mysql/user.ibd" ]; then
            echo "MySQL数据目录未初始化，开始初始化..."
            
            # 初始化MySQL数据目录
            mysqld --initialize-insecure \
              --user=999 \
              --datadir=/var/lib/mysql \
              --basedir=/usr \
              --character-set-server=utf8mb4 \
              --collation-server=utf8mb4_unicode_ci
            
            echo "MySQL数据目录初始化完成"
          else
            echo "MySQL数据目录已存在，跳过初始化"
          fi
          
          # 再次确保权限正确
          chown -R 999:999 /var/lib/mysql
          chmod -R 750 /var/lib/mysql
          
          echo "设置后的权限:"
          ls -la /var/lib/mysql
          echo "检查数据目录内容:"
          ls -la /var/lib/mysql/
          echo "=== 初始化完成 ==="
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      containers:
      - name: mysql
        image: mysql:8.0.39
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: ragflow-config
              key: MYSQL_PASSWORD
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: ragflow-config
              key: TIMEZONE
        command:
        - mysqld
        - --max_connections=1000
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --default-authentication-plugin=mysql_native_password
        - --tls_version=TLSv1.2,TLSv1.3
        - --init-file=/data/application/init.sql
        - --binlog_expire_logs_seconds=604800
        - --skip-host-cache
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: init-sql
          mountPath: /data/application/init.sql
          subPath: init.sql
        securityContext:
          runAsUser: 999
          runAsGroup: 999
          fsGroup: 999
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - mysqladmin ping -uroot -p$MYSQL_ROOT_PASSWORD
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - mysqladmin ping -uroot -p$MYSQL_ROOT_PASSWORD
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: init-sql
        configMap:
          name: mysql-init-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
  namespace: ragflow
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS rag_flow CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ragflow
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  type: ClusterIP
