apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  namespace: ragflow
  labels:
    app: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
      - name: opensearch
        image: hub.icert.top/opensearchproject/opensearch:2.19.1
        ports:
        - containerPort: 9201
        env:
        - name: node.name
          value: "opensearch01"
        - name: OPENSEARCH_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: ragflow-config
              key: OPENSEARCH_PASSWORD
        - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: ragflow-config
              key: OPENSEARCH_PASSWORD
        - name: bootstrap.memory_lock
          value: "false"
        - name: discovery.type
          value: "single-node"
        - name: plugins.security.disabled
          value: "false"
        - name: plugins.security.ssl.http.enabled
          value: "false"
        - name: plugins.security.ssl.transport.enabled
          value: "true"
        - name: cluster.routing.allocation.disk.watermark.low
          value: "5gb"
        - name: cluster.routing.allocation.disk.watermark.high
          value: "3gb"
        - name: cluster.routing.allocation.disk.watermark.flood_stage
          value: "2gb"
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: ragflow-config
              key: TIMEZONE
        - name: http.port
          value: "9201"
        volumeMounts:
        - name: os-data
          mountPath: /usr/share/opensearch/data
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 9201
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 120
        readinessProbe:
          httpGet:
            path: /
            port: 9201
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
      volumes:
      - name: os-data
        persistentVolumeClaim:
          claimName: opensearch-pvc
      securityContext:
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: ragflow
  labels:
    app: opensearch
spec:
  selector:
    app: opensearch
  ports:
  - name: opensearch
    port: 9201
    targetPort: 9201
  type: ClusterIP
